### ISSUE TITLE
PSR-0 Compatability

### ISSUE THREAD

**Issue by philsturgeon** [Sterling-Technologies/eden#17]
Hey guys,

While I am impressed with the amount of work and effort the 4 or 5 contributors have put into this project, it to me seems like a massive duplication of effort. 

I understand entirely that its nice to have a single "go-to" for PHP code, where all code is consistent throughout all libraries, but this is exactly what PSR-0 and PSR-1 were developed for. 

http://www.php-fig.org/

There is a substantial list of projects on there, including some of the largest in PHP.

All of those teams are moving towards using Consistent namespacing instead of using manual includes followed by weird invoke hacks or any of the following:

```
//Generic
new Eden_Session;
new Eden_Session();
Eden_Session::i();  

//Used outside of a class
eden('session');            
eden()->Session();       // alias
eden()->Eden_Session();

//Used in a class extended with Eden
$this->Session();        // alias
$this->Eden_Session();   
$this('session');       //PHP 5.3

/* Passing construct arguments */

//Generic
new Eden_Validation('something');
Eden_Validation::i('something');        //instantiate in a class

//Used outside of a class
eden('validation', 'something');        
eden()->Validation('something');     // alias
eden()->Eden_Validation('something');    

//Used in a class extended with Eden
$this->Validation('something');          // alias
$this->Eden_Validation('something'); 
$this('validation', 'something');       // PHP 5.3
```

This is a really weird collection of approaches to doing the exact same thing. Why is it being done this way?

```
new \Eden\Validation('something');
```

Tada, PSR-0 compatibility.

Furthermore, it is a massive shame that you guys are distributing this as one solid package. It would be substantially more useful to distribute this with Composer, meaning that instead of having to copy and paste specific files, then check for new versions later, and copy and paste the updated files every now and then... you could just run `$ composer update` and have any new changes pulled down.

You guys are doing a good job building an impressive library of components, but please don't ignore tools and conventions that have been made available with the express purpose of helping projects like this one.

I would be very interested in seeing you accept PSR-0 for the next version, with the view of moving to PSR-1 (at least) in the future. If anyone reading this agrees then please +1.

**Comment by nikkobautista** [comment]
Hey Phil,

Based on my knowledge on the project, PSR-0 and PSR-1 compatibility is in
roadmap. The company behind the Eden, Openovate labs has a lot of other
projects in the pipeline as well, which is why this was open sourced so
people can contribute.

I'd love to hear Christian's (@cblanquera)  thoughts on the matter though, so I would
leave it up to him to explain further. (Christian Blanquera was the
original author of Eden)
:+1:

**Comment by nicholasruunu** [comment]
:+1:

**Comment by frankmayer** [comment]
:+1:

**Comment by raftalks** [comment]
:+1:

**Comment by toin0u** [comment]
:+1:

**Comment by cblanquera** [comment]
I like to stay away from the "new" word and namespaces because it's another line of code. With the "new" word also implies you need to assign it to a variable. There are different ways to instantiate classes in Eden because in my experiences with working in different kind of companies, apparently there are different ways of doing things. 

The instantiation methods you provided are not hacks at all. In Eden you can overwrite classes previously defined by someone else, without modifying the original code. See: http://eden.openovate.com/documentation/core/classes . 
However using "new" or name spacing would not make this feature possible. 

Some people say things are "weird" or "hackish" if it's new to them, disruptive or if some popular guy didn't say it was cool. 

The point of Eden is to get going fast. I taught Eden to a group of novice girl developers last year and they were able to build twitter, facebook, google etc.. mashups in 2 hours. I sat through a Facebook API workshop with James Pierce (Facebook's API Evangelist), a whole day on the Graph and FQL API :(

Every project we did in my company last year with Eden took no more than 3 weeks to dev. Our sprints are literally no more than 2 days. Eden isn't just a collection of API libraries. We thought about how a developer programs and came up with ways to reduce the amount of code you actually have to write to get things done. IMO things like new Mage_Core_Model_Session_Abstract_Varien is a waste of mind space. 

Though it would be nice everyone codes the same way, the facebook SDK and twiiter PHP aren't built in a "standard" way. And if there are libraries someone wrote for a 3rd party API, it's usually incomplete or you find yourself looking in the code to make sense of it all. Then when you look into the code there's no comments or coding conventions in that. and your the one to blame if it's not scalable or buggy, because you decided to use it. I've been through all of that for years, it's the reason why Eden exists. For a more standards kind of language there's always RoR.

But, PSR and Composer are in fact in our plans for Eden this quarter, just trying to free up some resources in my company to do so.

c

**Comment by philsturgeon** [comment]
> I like to stay away from the "new" word and namespaces because it's another line of code.

One line of code won't kill anybody, but in PHP 5.4 that is not even an issue thanks to instance dereferencing:

```
(new \Eden\Validation('something'))->someMethod();
```

Even with that said, using static factory methods to create your instances does not break PSR compatibility, so that's not an issue.

> There are different ways to instantiate classes in Eden because in my experiences with working in different kind of companies, apparently there are different ways of doing things.

I see no reason whatsoever why developing for a "different company" would mean a different autoloading solution needs to be used. I would absolutely love to see a blog with more information on that circumstance. 

> The instantiation methods you provided are not hacks at all. 

A hack is like a weed, if its expected then it's a plant, if its not expected then it's a weed. Nobody else in the PHP community is expecting this behaviour.

> Some people say things are "weird" or "hackish" if it's new to them, disruptive or if some popular guy didn't say it was cool.

See above. 

> I taught Eden to a group of novice girl developers last year and they were able to build twitter, facebook, google etc.. mashups in 2 hours. 

Wow, you even managed to make "women" do it? I'm sure the whole female PHP community would LOVE to know about this, they've been struggling to handle PHP programming for years.

> Eden isn't just a collection of API libraries.

No it literally is just a collection of libraries, based on the fact that it's a folder that says libraries and there is a whole collection of stuff in there.

> IMO things like new Mage_Core_Model_Session_Abstract_Varien is a waste of mind space.

Yeah that looks terrible, nobody ever suggested you do anything like that. Please dont.

> Though it would be nice everyone codes the same way, the facebook SDK and twiiter PHP aren't built in a "standard" way. 

Agreed, the Facebook SDK and the Twitter API classes are mostly a piece of shit, this is why I would love to see you separate classes into PSR packages so everyone can enjoy them as a replacement to those dog-piles.

> For a more standards kind of language there's RoR.

That clearly has nothing to do with anything.

> But, PSR and Composer are in fact in our plans for Eden this quarter, just trying to free up some resources in my company to do so.

So after trying to make an argument about everything I said, you're planning on doing everything anyway? 

I wish you the best of luck. I can't wait to see Eden code on Packagist.

**Comment by dhrrgn** [comment]
> For a more standards kind of language there's RoR.

You know that RoR isn't a language...right? It is a framework, built in Ruby...

Also...[insert long rant here I don't want to waste my time writing]

**Comment by johnnncodes** [comment]
+1

**Comment by cblanquera** [comment]
Hey Phil, if i offended you in anyway, im sorry for that. You weren't the first person who asked for PSR and composer. It actually was a conversation on Reddit first sometime last year and I humbly accepted it. But if Eden is not to your liking, you can simply not use it. Anyways, your last comment was pretty condescending. Edit: Just read the end of that, thank you

**Comment by cblanquera** [comment]
Hey dandoescode, thanks for the RoR correction.

**Comment by philsturgeon** [comment]
It certainly was :)

I know usage is optional, but I genuinely believe it will be good for the PHP community in general when you make the switch. I'm generally chasing up anyone not using composer to do so.

Best of luck!

**Comment by markushausammann** [comment]
@philsturgeon it's great to see you're doing that (chasing up people) but IMHO your language can come accross as arrogant and condescending indeed. I don't know whether this has something to do with language culture, the british seem to talk to each other like that. but you're on an international platform here and I assure you that you'll be more successful when developing some cultural sensibility and adjusting your way of communication.

**Comment by hasokeric** [comment]
@philsturgeon PSR is the way to go, nice post.

**Comment by asifrust** [comment]
+1

**Comment by outrunthewolf** [comment]
So is this sorted now? PSR-0 compatible?
